channel: saturday-supercade
channel_number: 9
name: "Saturday Supercade"
channel_type: network
timezone: America/New_York

format:
  video: { width: 1280, height: 720, frame_rate: "30/1" }
  audio: { sample_rate: 48000, channels: 2 }
  grid_minutes: 30

filler: !include _defaults.yaml:filler

notes:
  vibe: "Saturday morning cartoons all week long"
  tagline: "Every Day Is Saturday."

pools:
  mario:
    match:
      type: episode
      series_title: "Super Mario World"
  xmen:
    match:
      type: episode
      series_title: "X-Men '97"
  smiling:
    match:
      type: episode
      series_title: "Smiling Friends"
  stooges:
    match:
      type: episode
      series_title: "The New Three Stooges"
  superman:
    match:
      type: episode
      series_title: "The Superman/Aquaman Hour of Adventure"
  pjs:
    match:
      type: episode
      series_title: "The PJs"

schedule:
  all_day:
    - block:
        start: "06:00"
        end: "06:00"
        title: "Cartoon Block"
        pool: [mario, superman, stooges, xmen, smiling, pjs]
        mode: shuffle
